import { SQLiteDatabase } from 'expo-sqlite';
import { AppSettings, EditorDraft, Environment, LaunchAttempt, PlatformTarget, ReportedResult, SavedLink } from '@/domain/types';

const env = (r: any): Environment => ({ id:r.id,name:r.name,baseUrl:r.base_url,customScheme:r.custom_scheme,isBuiltIn:!!r.is_built_in });
const saved = (r:any):SavedLink => ({ id:r.id,name:r.name,link:r.link,platform:r.platform,environmentId:r.environment_id,notes:r.notes,lastUsedAt:r.last_used_at,reportedResult:r.reported_result,createdAt:r.created_at,updatedAt:r.updated_at });
const attempt = (r:any):LaunchAttempt => ({ id:r.id,finalLink:r.final_link,attemptedAt:r.attempted_at,platform:r.platform,environmentId:r.environment_id,environmentName:r.environment_name,handoffResult:r.handoff_result,errorCode:r.error_code,errorMessage:r.error_message,reportedResult:r.reported_result,savedLinkId:r.saved_link_id });

export class Repository {
  constructor(private db: SQLiteDatabase) {}
  async environments(){ return (await this.db.getAllAsync('SELECT * FROM environments ORDER BY id')).map(env); }
  async savedLinks(){ return (await this.db.getAllAsync('SELECT * FROM saved_links ORDER BY COALESCE(last_used_at, created_at) DESC')).map(saved); }
  async history(){ return (await this.db.getAllAsync('SELECT * FROM launch_attempts ORDER BY attempted_at DESC')).map(attempt); }
  async sensitiveNames(){ return (await this.db.getAllAsync<{name:string}>('SELECT name FROM sensitive_parameter_names ORDER BY name')).map(r=>r.name); }
  async settings():Promise<AppSettings>{ const r:any=await this.db.getFirstAsync('SELECT * FROM settings WHERE id=1'); return {defaultPlatform:r.default_platform,defaultEnvironmentId:r.default_environment_id,confirmBeforeOpen:!!r.confirm_before_open,reopenLastLink:!!r.reopen_last_link,maskSensitive:!!r.mask_sensitive,retentionDays:r.retention_days,appearance:r.appearance}; }
  async draft():Promise<EditorDraft>{ const r:any=await this.db.getFirstAsync('SELECT * FROM editor_state WHERE id=1'); return {link:r.link,platform:r.platform,environmentId:r.environment_id,savedLinkId:r.saved_link_id}; }
  async saveDraft(d:EditorDraft){ await this.db.runAsync('UPDATE editor_state SET link=?, platform=?, environment_id=?, saved_link_id=? WHERE id=1',d.link,d.platform,d.environmentId,d.savedLinkId); }
  async saveLink(input:{id?:number;name:string;link:string;platform:PlatformTarget;environmentId:number|null;notes:string}){ const now=new Date().toISOString(); if(input.id){await this.db.runAsync('UPDATE saved_links SET name=?,link=?,platform=?,environment_id=?,notes=?,updated_at=? WHERE id=?',input.name,input.link,input.platform,input.environmentId,input.notes,now,input.id);return input.id;} const r=await this.db.runAsync('INSERT INTO saved_links(name,link,platform,environment_id,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',input.name,input.link,input.platform,input.environmentId,input.notes,now,now); return r.lastInsertRowId; }
  async deleteSaved(id:number){ await this.db.runAsync('DELETE FROM saved_links WHERE id=?',id); }
  async saveEnvironment(input:{id?:number;name:string;baseUrl:string;customScheme:string|null}){if(input.id){await this.db.runAsync('UPDATE environments SET name=?,base_url=?,custom_scheme=?,updated_at=? WHERE id=?',input.name,input.baseUrl,input.customScheme,new Date().toISOString(),input.id);return input.id;}const r=await this.db.runAsync('INSERT INTO environments(name,base_url,custom_scheme,is_built_in) VALUES(?,?,?,0)',input.name,input.baseUrl,input.customScheme);return r.lastInsertRowId;}
  async deleteEnvironment(id:number){await this.db.runAsync('DELETE FROM environments WHERE id=? AND is_built_in=0',id);}
  async addSensitiveName(name:string){await this.db.runAsync('INSERT OR IGNORE INTO sensitive_parameter_names(name) VALUES(?)',name.trim().toLowerCase());}
  async deleteSensitiveName(name:string){await this.db.runAsync('DELETE FROM sensitive_parameter_names WHERE name=?',name);}
  async createAttempt(input:{link:string;platform:PlatformTarget;environmentId:number|null;environmentName:string;savedLinkId:number|null}){ const now=new Date().toISOString(); const r=await this.db.runAsync("INSERT INTO launch_attempts(final_link,attempted_at,platform,environment_id,environment_name,handoff_result,saved_link_id) VALUES(?,?,?,?,?,'pending',?)",input.link,now,input.platform,input.environmentId,input.environmentName,input.savedLinkId); if(input.savedLinkId) await this.db.runAsync('UPDATE saved_links SET last_used_at=? WHERE id=?',now,input.savedLinkId); return r.lastInsertRowId; }
  async finishAttempt(id:number,result:'succeeded'|'failed',errorCode?:string,errorMessage?:string){ await this.db.runAsync('UPDATE launch_attempts SET handoff_result=?,error_code=?,error_message=? WHERE id=?',result,errorCode??null,errorMessage??null,id); }
  async reportAttempt(id:number,result:ReportedResult){ await this.db.runAsync('UPDATE launch_attempts SET reported_result=? WHERE id=?',result,id); }
  async deleteAttempt(id:number){await this.db.runAsync('DELETE FROM launch_attempts WHERE id=?',id);}
  async clearHistory(){await this.db.runAsync('DELETE FROM launch_attempts');}
  async updateSettings(s:AppSettings){await this.db.runAsync('UPDATE settings SET default_platform=?,default_environment_id=?,confirm_before_open=?,reopen_last_link=?,mask_sensitive=?,retention_days=?,appearance=? WHERE id=1',s.defaultPlatform,s.defaultEnvironmentId,+s.confirmBeforeOpen,+s.reopenLastLink,+s.maskSensitive,s.retentionDays,s.appearance);}
  async purgeHistory(days:number){if(days>0)await this.db.runAsync("DELETE FROM launch_attempts WHERE attempted_at < datetime('now', ?)",`-${days} days`);}
  async resetAll(){await this.db.withExclusiveTransactionAsync(async(tx)=>{await tx.execAsync("DELETE FROM launch_attempts; DELETE FROM saved_links; DELETE FROM sensitive_parameter_names; DELETE FROM environments; DELETE FROM sqlite_sequence WHERE name='environments'; INSERT INTO environments (name,base_url,custom_scheme,is_built_in) VALUES ('Development','https://dev.example.com','myapp-dev',1),('Staging','https://staging.example.com','myapp-staging',1),('Production','https://example.com','myapp',1); UPDATE settings SET default_platform='ios',default_environment_id=1,confirm_before_open=0,reopen_last_link=0,mask_sensitive=1,retention_days=30,appearance='system' WHERE id=1; UPDATE editor_state SET link='',platform='ios',environment_id=1,saved_link_id=NULL WHERE id=1; INSERT INTO sensitive_parameter_names(name) VALUES ('token'),('access_token'),('auth'),('authorization'),('api_key'),('code'),('password'),('secret'),('signature'),('sig');");});}
}
