import { SymbolView, SymbolViewProps } from 'expo-symbols';
import { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, TextInputProps, View, ViewProps } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { fonts, palette, radius, spacing } from '@/constants/theme';
import { useAppData } from '@/context/app-context';

export function Screen({children,scroll=true,title,subtitle,action}:{children:ReactNode;scroll?:boolean;title:string;subtitle?:string;action?:ReactNode}){
  const {colors,error,reload}=useAppData();const inset=useSafeAreaInsets();const content=<View style={[s.content,{paddingTop:inset.top+spacing.lg}]}><View style={s.headingRow}><View style={{flex:1}}><Text style={[s.title,{color:colors.ink}]}>{title}</Text>{subtitle?<Text style={[s.subtitle,{color:colors.muted}]}>{subtitle}</Text>:null}</View>{action}</View>{error?<View accessibilityRole="alert" style={[s.errorBanner,{backgroundColor:palette.blush}]}><View style={{flex:1}}><Text style={[s.errorTitle,{color:palette.danger}]}>Local operation failed</Text><Text style={{color:colors.ink}}>{error}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Retry local operation" onPress={reload}><Text style={{color:palette.blue,fontWeight:'600'}}>Retry</Text></Pressable></View>:null}{children}</View>;
  return scroll?<ScrollView style={{flex:1,backgroundColor:colors.canvas}} contentContainerStyle={{paddingBottom:128}} keyboardShouldPersistTaps="handled">{content}</ScrollView>:<View style={{flex:1,backgroundColor:colors.canvas}}>{content}</View>;
}
export function Card({children,style,tint}:PropsWithChildren<{style?:ViewProps['style'];tint?:string}>){const{colors}=useAppData();return <View style={[s.card,{backgroundColor:tint??colors.surface},style]}>{children}</View>}
export function Label({children}:PropsWithChildren){const{colors}=useAppData();return <Text style={[s.label,{color:colors.muted}]}>{children}</Text>}
export function Body({children,style}:PropsWithChildren<{style?:any}>){const{colors}=useAppData();return <Text style={[s.body,{color:colors.ink},style]}>{children}</Text>}
export function Mono({children,numberOfLines}:PropsWithChildren<{numberOfLines?:number}>){const{colors}=useAppData();return <Text numberOfLines={numberOfLines} style={[s.mono,{color:colors.ink}]}>{children}</Text>}
export function Field(props:TextInputProps){const{colors}=useAppData();return <TextInput placeholderTextColor={colors.muted} {...props} style={[s.field,{color:colors.ink,backgroundColor:colors.surfaceMuted,borderColor:colors.border},props.style]}/>}
export function Button({label,onPress,kind='primary',disabled=false,icon}: {label:string;onPress:()=>void;kind?:'primary'|'secondary'|'danger';disabled?:boolean;icon?:SymbolViewProps['name']}){const{colors}=useAppData();const bg=kind==='primary'?palette.blue:kind==='danger'?palette.blush:colors.surface;const fg=kind==='primary'?'#fff':kind==='danger'?palette.danger:palette.blue;return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,{backgroundColor:bg,opacity:disabled?.4:1,transform:[{scale:pressed?.98:1}]}]}>{icon?<SymbolView name={icon} size={17} tintColor={fg}/>:null}<Text style={[s.buttonText,{color:fg}]}>{label}</Text></Pressable>}
export function IconButton({label,onPress,name}: {label:string;onPress:()=>void;name:SymbolViewProps['name']}){const{colors}=useAppData();return <Pressable hitSlop={8} accessibilityLabel={label} accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.iconButton,{backgroundColor:colors.surfaceMuted,opacity:pressed?.65:1,transform:[{scale:pressed?.94:1}]}]}><SymbolView name={name} size={18} tintColor={palette.blue}/></Pressable>}
export function Pill({label,selected=false,onPress,tint}: {label:string;selected?:boolean;onPress?:()=>void;tint?:string}){const{colors}=useAppData();return <Pressable disabled={!onPress} onPress={onPress} style={[s.pill,{backgroundColor:selected?palette.blue:(tint??colors.surfaceMuted)}]}><Text style={[s.pillText,{color:selected?'#fff':colors.ink}]}>{label}</Text></Pressable>}
export function Empty({title,body}: {title:string;body:string}){const{colors}=useAppData();return <View style={s.empty}><SymbolView name={{ios:'link',android:'link'}} size={22} tintColor={colors.muted}/><Body style={{fontSize:17,fontWeight:'600'}}>{title}</Body><Text style={[s.subtitle,{color:colors.muted,textAlign:'center'}]}>{body}</Text></View>}
export function Loading(){return <View style={s.loading}><ActivityIndicator color={palette.blue}/></View>}

const s=StyleSheet.create({content:{paddingHorizontal:16,gap:12},headingRow:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:4},title:{fontSize:34,lineHeight:41,fontWeight:'700',letterSpacing:-.4},subtitle:{fontSize:15,lineHeight:20,marginTop:2},errorBanner:{borderRadius:radius.md,padding:12,flexDirection:'row',alignItems:'center',gap:12},errorTitle:{fontSize:14,fontWeight:'600',marginBottom:2},card:{borderRadius:radius.lg,padding:spacing.lg,gap:10},label:{fontSize:13,lineHeight:17,fontWeight:'600',letterSpacing:0},body:{fontSize:17,lineHeight:22,fontWeight:'400'},mono:{fontFamily:fonts.mono,fontSize:13,lineHeight:18},field:{borderRadius:radius.md,borderWidth:StyleSheet.hairlineWidth,paddingHorizontal:12,paddingVertical:11,fontSize:17,minHeight:44},button:{minHeight:50,borderRadius:radius.md,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},buttonText:{fontSize:17,fontWeight:'600'},iconButton:{height:40,width:40,borderRadius:20,alignItems:'center',justifyContent:'center'},pill:{borderRadius:radius.pill,paddingHorizontal:12,paddingVertical:7},pillText:{fontSize:13,fontWeight:'600'},empty:{alignItems:'center',paddingVertical:24,paddingHorizontal:28,gap:7},loading:{flex:1,alignItems:'center',justifyContent:'center'}});
