import * as Clipboard from 'expo-clipboard';
import * as Linking from 'expo-linking';
import { router } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, AppState, Modal, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Field, IconButton, Label, Mono, Screen } from '@/components/ui';
import { palette } from '@/constants/theme';
import { useAppData } from '@/context/app-context';
import { parseLink, withQueryParameters } from '@/domain/link-utils';
import { PlatformTarget, QueryParameter, ReportedResult } from '@/domain/types';
import { copyText, readClipboardText } from '@/utils/clipboard';

export default function EditorScreen(){
 const {colors,draft,setDraft,savedLinks,history,repo,reload,settings}=useAppData(); const raw=draft.link; const platform:PlatformTarget=Platform.OS==='android'?'android':'ios'; const [saveOpen,setSaveOpen]=useState(false); const [name,setName]=useState(''); const [notes,setNotes]=useState(''); const [feedbackId,setFeedbackId]=useState<number|null>(null); const pending=useRef<number|null>(null); const leftApp=useRef(false);
 const parsed=useMemo(()=>parseLink(raw),[raw]);
 const isEmpty=!raw.trim();
 const recent=useMemo(()=>{const seen=new Set<string>();return history.filter(item=>{if(seen.has(item.finalLink))return false;seen.add(item.finalLink);return true;}).slice(0,3);},[history]);
 const updateRaw=(link:string)=>{void setDraft({...draft,link});};
 const report=useCallback(async(id:number,result:ReportedResult)=>{setFeedbackId(null);await repo.reportAttempt(id,result);await reload();},[repo,reload]);
 useEffect(()=>{const sub=AppState.addEventListener('change',(state)=>{if(state!=='active')leftApp.current=true;if(state==='active'&&leftApp.current&&pending.current){setFeedbackId(pending.current);pending.current=null;leftApp.current=false;}});return()=>sub.remove();},[]);
 const setParams=(params:QueryParameter[])=>{if(parsed.valid)updateRaw(withQueryParameters(raw,params));};
 const launch=async(link:string,savedLinkId:number|null)=>{const id=await repo.createAttempt({link,platform,environmentId:null,environmentName:'This device',savedLinkId});await reload();try{await Linking.openURL(link);await repo.finishAttempt(id,'succeeded');pending.current=id;await reload();}catch(error){await repo.finishAttempt(id,'failed','handoff_failed',error instanceof Error?error.message:'The operating system could not open this link.');await reload();Alert.alert('Handoff failed','No compatible destination accepted the link.',[{text:'Edit'},{text:'Copy',onPress:()=>void copyText(link)},{text:'Retry',onPress:()=>void launch(link,savedLinkId)}]);}};
 const open=()=>{if(!parsed.valid)return;const link=raw.trim();if(settings.confirmBeforeOpen)Alert.alert('Open this link?',link,[{text:'Cancel',style:'cancel'},{text:'Open',onPress:()=>void launch(link,draft.savedLinkId)}]);else void launch(link,draft.savedLinkId);};
 const persistSave=async()=>{await repo.saveLink({id:draft.savedLinkId??undefined,name:name.trim(),link:raw.trim(),platform,environmentId:null,notes:notes.trim()});setSaveOpen(false);setName('');setNotes('');await reload();};
 const save=()=>{if(!name.trim()||!parsed.valid)return;if(draft.savedLinkId)Alert.alert('Replace saved link?','This updates the existing Saved Link with the current editor values.',[{text:'Cancel',style:'cancel'},{text:'Replace',onPress:persistSave}]);else void persistSave();};
 return <Screen title="Link" subtitle="Paste a URL or app scheme to test it.">
   <Card><View style={s.row}><View style={{flex:1}}><Label>Link</Label></View>{!isEmpty?<><IconButton label="Copy link" name={{ios:'doc.on.doc',android:'content_copy'} as any} onPress={()=>void copyText(raw)}/><IconButton label="Clear link" name={{ios:'xmark',android:'close'} as any} onPress={()=>updateRaw('')}/></>:null}</View><Field value={raw} onChangeText={updateRaw} multiline autoCapitalize="none" autoCorrect={false} placeholder="https://example.com/path or myapp://path" style={{minHeight:72,fontFamily:'monospace',textAlignVertical:'top'}}/>{isEmpty?(Platform.OS==='ios'&&Clipboard.isPasteButtonAvailable?<Clipboard.ClipboardPasteButton acceptedContentTypes={['plain-text']} displayMode="iconAndLabel" cornerStyle="fixed" backgroundColor={palette.blue} foregroundColor="#FFFFFF" style={s.nativePaste} onPress={data=>{if(data.type==='text')updateRaw(data.text);}}/>:<Button label="Paste from Clipboard" icon={{ios:'doc.on.clipboard',android:'content_paste'} as any} onPress={async()=>{const value=await readClipboardText();if(value)updateRaw(value);}}/>):null}{!isEmpty?<View style={s.validation}><SymbolView name={{ios:parsed.valid?'checkmark.circle.fill':'exclamationmark.circle.fill',android:parsed.valid?'check_circle':'error'} as any} size={16} tintColor={parsed.valid?palette.success:palette.danger}/><Text style={[s.validationText,{color:parsed.valid?palette.success:palette.danger}]}>{parsed.valid?'Ready to open':parsed.message}</Text></View>:null}</Card>
   {feedbackId?<Card tint={palette.blueSoft}><Label>Did the expected screen open?</Label><Text style={{color:colors.muted}}>Your answer is recorded as feedback, not automatic verification.</Text><View style={s.feedbackRow}>{(['yes','no','not_sure'] as const).map(value=><Pressable key={value} accessibilityRole="button" accessibilityLabel={value==='not_sure'?'Not sure':value} onPress={()=>void report(feedbackId,value)} style={({pressed})=>[s.feedbackChoice,{backgroundColor:colors.surface,opacity:pressed?.65:1}]}><Text style={{color:palette.blue,fontWeight:'600'}}>{value==='not_sure'?'Not sure':value[0].toUpperCase()+value.slice(1)}</Text></Pressable>)}</View></Card>:null}
   {parsed.valid?<><Card><Label>Parsed values</Label>{[['Scheme',parsed.scheme],['Host',parsed.host||'—'],['Path',parsed.path],['Fragment',parsed.fragment||'—']].map(([k,v])=><View key={k} style={s.parsed}><Text style={{color:colors.muted}}>{k}</Text><Mono numberOfLines={1}>{v}</Mono></View>)}</Card>
   <Card><View style={s.row}><View style={{flex:1}}><Label>Query parameters</Label></View><IconButton label="Add parameter" name={{ios:'plus',android:'add'} as any} onPress={()=>setParams([...parsed.params,{id:`new-${Date.now()}`,key:'key',value:''}])}/></View>{parsed.params.length?parsed.params.map((p,i)=><View key={`${p.id}-${i}`} style={s.param}><Field value={p.key} onChangeText={key=>setParams(parsed.params.map((x,j)=>j===i?{...x,key}:x))} placeholder="key" style={{flex:.8}}/><Field value={p.value} onChangeText={value=>setParams(parsed.params.map((x,j)=>j===i?{...x,value}:x))} placeholder="value" style={{flex:1}}/><IconButton label={`Delete ${p.key}`} name={{ios:'trash',android:'delete'} as any} onPress={()=>setParams(parsed.params.filter((_,j)=>j!==i))}/></View>):<Text style={{color:colors.muted}}>No query parameters yet.</Text>}</Card></>:null}
   {parsed.valid?<View style={s.actions}><Button label="Open Link" icon={{ios:'arrow.up.forward.app',android:'open_in_new'} as any} onPress={open}/><View style={s.secondaryRow}><View style={{flex:1}}><Button label="Save" kind="secondary" icon={{ios:'bookmark',android:'bookmark'} as any} onPress={()=>{const existing=savedLinks.find(l=>l.id===draft.savedLinkId);setName(existing?.name??'');setNotes(existing?.notes??'');setSaveOpen(true)}}/></View><View style={{flex:1}}><Button label="Command" kind="secondary" icon={{ios:'terminal',android:'terminal'} as any} onPress={()=>router.push('/command')}/></View></View></View>:null}
   {recent.length?<Card><Label>Recent</Label>{recent.map(item=><Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Open again ${item.finalLink}`} onPress={()=>void launch(item.finalLink,item.savedLinkId)} style={({pressed})=>[s.recentRow,{opacity:pressed?.55:1}]}><Mono numberOfLines={1}>{item.finalLink}</Mono><SymbolView name={{ios:'arrow.up.forward',android:'open_in_new'} as any} size={16} tintColor={palette.blue}/></Pressable>)}</Card>:null}
   <Modal visible={saveOpen} transparent animationType="slide" onRequestClose={()=>setSaveOpen(false)}><Pressable style={s.scrim} onPress={()=>setSaveOpen(false)}/><View style={[s.sheet,{backgroundColor:colors.canvas}]}><Text style={[s.sheetTitle,{color:colors.ink}]}>Save Link</Text><Field value={name} onChangeText={setName} placeholder="Link name" autoFocus/><Field value={notes} onChangeText={setNotes} placeholder="Notes (optional)" multiline/><Button label={draft.savedLinkId?'Update Saved Link':'Save Link'} disabled={!name.trim()} onPress={save}/><Button label="Cancel" kind="secondary" onPress={()=>setSaveOpen(false)}/></View></Modal>
  </Screen>
}
const s=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',gap:8},nativePaste:{height:50,width:'100%'},validation:{flexDirection:'row',alignItems:'center',gap:6},validationText:{fontSize:13,lineHeight:17,fontWeight:'600'},feedbackRow:{flexDirection:'row',gap:8},feedbackChoice:{flex:1,minHeight:40,borderRadius:10,alignItems:'center',justifyContent:'center'},recentRow:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},parsed:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingVertical:4},param:{flexDirection:'row',alignItems:'center',gap:8},actions:{gap:8},secondaryRow:{flexDirection:'row',gap:8},scrim:{position:'absolute',left:0,right:0,top:0,bottom:0,backgroundColor:'#0006'},sheet:{position:'absolute',left:0,right:0,bottom:0,borderTopLeftRadius:20,borderTopRightRadius:20,padding:20,paddingBottom:40,gap:12},sheetTitle:{fontSize:28,lineHeight:34,fontWeight:'700',letterSpacing:-.3},});
